### PR TITLE
template: Replace paginated grid with collapsible variant

### PR DESCRIPTION
**Pull request by manuq**
In all remaining cases.

https://phabricator.endlessm.com/T32151

### CODE REVIEW

**Review by erikos — APPROVED** [review]
Looks good!

**Comment by manuq** [comment]
> Looks good!

I now updated it to fix the initial cards regression.

**Comment by erikos** [comment]
Took another look, the logic seems fine on the show-less/show-more and the number of grid items.

**Comment by erikos** [comment]
> > Looks good!
> 
> I now updated it to fix the initial cards regression.

Yes, already checked :)

**Pull request merged**
