### PR TITLE
T31260 content page

### PR DESCRIPTION
**Pull request by manuq**
https://phabricator.endlessm.com/T31260

### CODE REVIEW

**Review by danigm — APPROVED** [review]
LGTM

**Review by danigm — APPROVED** [review]
LGTM

**Comment by manuq** [comment]
> LGTM

After a while working on this I was expecting more from the review :-P Thanks anyways for looking :+1:

**Comment by danigm** [comment]
> > LGTM
> 
> After a while working on this I was expecting more from the review :-P Thanks anyways for looking +1

We've been trying different solutions here, and at the end, I think it's okay to go with this implementation, this solution looks good to me and it works correctly.

I know that the LGTM comment is not too much feedback, I could leave a comments about some details, for example the movement of the background url string build in the handler instead of the component methods, but at the end I think it's a good solution and I didn't want to start a discussion just for this kind of tech decisions.

**Pull request merged**
