### PR TITLE
New overrides

### LINKED ISSUE #878: Channel override: Biblioteca Elejandria
Channel ID: dosis-vukov

Styling:
- [ ] Custom thumbnail? Provide JPEG file for the channel card
- [ ] Custom icon? Provide PNG that will replace the channel icon uploaded at Kolibri Studio
https://www.dropbox.com/sh/bye62xtoquq0f67/AADqXBctIM30ghmBqbgP-Cf1a?dl=0

Options:
- [ ] Has carousel section? NO

image

### PR DESCRIPTION
**Pull request by manuq**
Fixes #878 #879 #880 #881 #882 #883 #884

### CODE REVIEW

**Review by dylanmccall — APPROVED** [review]
Okay, this seems good, but it looks like this increases the size of apps-bundle.zip from 64.9 MB to 70.8 MB. Hopefully won't be an issue _quite_ yet, but https://github.com/endlessm/kolibri-installer-android/pull/195 makes me a little wary. I wonder if we can trim any old channel overrides to delay the inevitable a little while longer? :)

**Comment by manuq** [comment]
> Okay, this seems good, but it looks like this increases the size of apps-bundle.zip from 64.9 MB to 70.8 MB. Hopefully won't be an issue _quite_ yet, but [endlessm/kolibri-installer-android#195](https://github.com/endlessm/kolibri-installer-android/pull/195) makes me a little wary. Let's keep an eye on how this ends up over there. I wonder if we can trim any old channel overrides to delay the inevitable a little while longer? :)

Yeah I've been warning about this for a while. Each custom presentation adds some more MB. I think I can compare the current collections and see if we have abandoned presentations, then ask Joana/Heather to confirm if we can remove them.

**Comment by manuq** [comment]
I have identified the following custom presentations as abandoned (for channels that are not in any collection):
```
abandoned custom presentations (for channel with id):
khan-academy (c9d7f950ab6b5a1199e3d6c10d7f0103)
open-stax (fc47aee82e0153e2a30197d3fdee1128)
pbs-kids (38eaaf9ec82a44f9ab6e7a44cb730f07)
terminal-two (3160899a73564d8a8467284d9219b91c)
coronavirus (c8540424d77f44f8ae306e22d3b14eaf)
gaming (57e23812e0dc562581958e39acedd717)
lgbtq (9eeebbc5140d5b98ac4a4d2ce9432135)
reading (59bb2e5a3d2e5e3b85b87d9ab4daa2f3)
staff-playlist (92e96efc082e5c62b0aac3847bdcdb33)
code-org (6da97a60cbd44e918137827bd5425efb)
wikipedia (f62db29be20453c4a267132e93a9e602)
wikihow-arts-and-entertainment (58828121cc115549bda7fb3f71f4795e)
wikihow-cars-and-other-vehicles (05a4060cf5175df78edec8dc09e396a1)
wikihow-computers-and-electronics (69497db42937539e94fe3969f6995d2d)
wikihow-education-and-communications (00b0d8dff13e518d801ef816227b2691)
wikihow-food-and-entertaining (b9fe8fe9b92b5af5964feccdadb78413)
wikihow-hobbies-and-crafts (e114fe9de66e513384e4ca2e9b529c18)
wikihow-holidays-and-traditions (9c494b7b879e512f96f60176df85968c)
wikihow-home-and-garden (304d529d4b1c597ea7d3c59b30ac3c14)
wikihow-personal-care-and-style (afbf0498da3c5db3947c291ddda8e21a)
wikihow-sports-and-fitness (146efed5aa585229a49513219e73af66)
wikihow-work-world (e4e4d0e342f951b09aa9ef1622f5301f)
wikihow-youth (6f6dd2720bd2574fa70a069ac9b75046)

custom presentations count: 65
channels in collections count: 51
abandoned presentations count: 23
```

**Comment by manuq** [comment]
@dylanmccall I have updated the PR with a commit that removes some discontinued channels. After this, the list of channels not in collections but with a custom presentation will be:
* open-stax
* terminal-two
* gaming
* staff-playlist
* wikipedia

I guess Joana wants to keep them because of their presence online instance.

**Comment by dylanmccall** [comment]
Nice! Thank you for taking care of that. I'll go ahead and merge this now :)

**Pull request merged**
