### PR TITLE
Bump kolibri tools

### PR DESCRIPTION
**Pull request by manuq**
Issue: #568

### CODE REVIEW

**Comment by manuq** [comment]
@GeorgesStavracas @jprvita please note that since this changes a frontend dependency you will have to run `yarn install` again in your local checkouts after it's merged.

**Review by jprvita — CHANGES_REQUESTED** [review]
@manuq is `yarn.lock` supposed to be checked-in to the repository? (IDK what it is used for, but the names suggests to me that it was auto-generated)

Other than that, LGTM (but I haven't tested it)

**Comment by jprvita** [comment]
I'm seeing this error, even after running `yarn install`:
```
(kolibri-py3.9) jprvita@endless:~/src/kolibri-explore-plugin$ yarn dev
yarn run v1.22.19
$ kolibri-tools build dev --plugins kolibri_explore_plugin --port 4000
Gathering relevant modules from ['kolibri_explore_plugin']
Writing webpack_json output to /tmp/2023513-420922-1ruhevk.8pz4.json
Error: ENOENT: no such file or directory, open '/sysroot/home/jprvita/src/kolibri-explore-plugin/kolibri/core/assets/src/core-app/apiSpec.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at specModule (/sysroot/home/jprvita/src/kolibri-explore-plugin/node_modules/kolibri-tools/lib/apiSpecExportTools.js:37:26)
    at Object.<anonymous> (/sysroot/home/jprvita/src/kolibri-explore-plugin/node_modules/kolibri-tools/lib/apiSpecExportTools.js:103:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/sysroot/home/jprvita/src/kolibri-explore-plugin/kolibri/core/assets/src/core-app/apiSpec.js'
}
```
I also have this message in `template-ui`, in addition to a message similar to the one above during building (before the build clearing the screen).
```
 warning  in ./src/dynamicLoadComponents.js

Module not found: Error: Can't resolve '@/overrides/components' in '/sysroot/home/jprvita/src/kolibri-explore-plugin/packages/template-ui/src'
```

**Comment by manuq** [comment]
@jprvita Richard says that this is just a console.log of a caught error that will be resolved in a future release. So I'm merging it.

**Comment by erikos** [comment]
Deployed in Ladybird 6.9-339 to internal testing.

**Pull request merged**
