### PR TITLE
WIP: Download: Import extra channels in the background

### PR DESCRIPTION
**Pull request by dylanmccall**
Issue #548

### CODE REVIEW

**Comment by dbnicholson** [comment]
FYI, I'm going to steal the blocking/completed difference for #584.

**Comment by dbnicholson** [comment]
I also wanted to say that after reading #608, I think that's the direction all of this downloading should move in. I.e., only use the backend helper for computing the tasks but have the frontend manage the tasks and the download state transitions.

**Comment by dbnicholson** [comment]
I tried out the method used here and it didn't work. Without directly enqueing the tasks you rely on the frontend to iterate the state machine, but then it's by definition not in the background.

**Comment by dylanmccall** [comment]
I believe this has been superseded by #650 (that one needs a bit of work still, but this one would need _a lot_ of work).

**Pull request closed without merging**
