### PR TITLE
welcome-screen: Update background assets

### PR DESCRIPTION
**Pull request by jprvita**
New assets provided by design, which should work well accross different languages.

https://github.com/endlessm/kolibri-explore-plugin/issues/756

### CODE REVIEW

**Comment by jprvita** [comment]
I think this is all that is needed here. I'm not sure how to test it though, as I don't have a access to a Chromebook right now, and this welcome screen is skipped in the dev environment.

**Comment by dylanmccall** [comment]
One convenient way to test this is with `lerna run serve --scope welcome-screen` from the project's base directory, which runs the thing at http://localhost:8080. I went ahead and did that, advancing to the welcome page by running `WelcomeApp.showWelcome() ` in the Javascript console, and this all looks good to me :)

For reference, here is the old one:

Screen Shot 2023-08-17 at 17 36 10

And here is the new one:

Screen Shot 2023-08-17 at 17 34 10

**Comment by dylanmccall** [comment]
As you can see, these assets are a smidge different in shape than the originals. Let's double check in #756 if that is intentional, but I'll mark this approved for now since it's doing what it says :)

**Review by dylanmccall — APPROVED** [review]

**Comment by jofilizola** [comment]
I've exported cropped assets! https://github.com/endlessm/kolibri-explore-plugin/issues/756#issuecomment-1683828013

**Comment by jprvita** [comment]
> One convenient way to test this is with `lerna run serve --scope welcome-screen` from the project's base directory, which runs the thing at http://localhost:8080. I went ahead and did that, advancing to the welcome page by running `WelcomeApp.showWelcome() ` in the Javascript console, and this all looks good to me :)

Thanks! I had gotten close by running `yarn serve` from `packages/welcome-screen`, but was missing the `WelcomeApp.showWelcome()` bit. I'm guessing `lerna` is a different tool to do roughly the same thing.

Converting back to draft while I update with the new assets.

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by jprvita** [comment]
Updated with newer assets, see https://github.com/endlessm/kolibri-explore-plugin/issues/756#issuecomment-1683995730 for how it looks and more info.

**Pull request merged**
