### PR TITLE
build: Add missing babel config for root package

### PR DESCRIPTION
**Pull request by pwithnall**
This was missing, meaning the default babel config was being used when
building the whole of kolibri-explore-plugin.

This meant that transpilation and ES5 polyfills were not being applied.

Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>

Fixes: https://github.com/endlessm/kolibri-installer-android/issues/159

### CODE REVIEW

**Comment by pwithnall** [comment]
For my own future reference, if nothing else, because it took a while to pin this one down:

The key debugging tool here was the [`BABEL_SHOW_CONFIG_FOR` environment variable](https://babeljs.io/docs/configuration#print-effective-configs).

Running `BABEL_SHOW_CONFIG_FOR=/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js yarn build` gave:
```
Babel configs on "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js" (ascending priority):
programmatic options from babel-loader
{
  "assumptions": {},
  "filename": "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js",
  "sourceMaps": true,
  "sourceFileName": "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  },
  "targets": {
    "android": "37.0.0",
    "chrome": "49.0.0",
    "edge": "18.0.0",
    "firefox": "52.0.0",
    "ie": "11.0.0",
    "ios": "9.3.0",
    "opera": "67.0.0",
    "safari": "11.1.0",
    "samsung": "4.0.0"
  },
  "cloneInputAst": true,
  "babelrc": false,
  "configFile": false,
  "browserslistConfigFile": false,
  "passPerPreset": false,
  "envName": "development",
  "cwd": "/home/philip/Projects/kolibri-explore-plugin",
  "root": "/home/philip/Projects/kolibri-explore-plugin",
  "rootMode": "root",
  "plugins": [],
  "presets": []
}
```

but running `BABEL_SHOW_CONFIG_FOR=/home/philip/Projects/kolibri/packages/kolibri-common/components/GlobalSnackbar.vue yarn build` gave:
```
Babel configs on "/home/philip/Projects/kolibri/packages/kolibri-common/components/GlobalSnackbar.vue" (ascending priority):
config /home/philip/Projects/kolibri/babel.config.js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": "3.31"
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-import-assertions"
  ],
  "sourceType": "unambiguous"
}

programmatic options from babel-loader
{
  "filename": "/home/philip/Projects/kolibri/packages/kolibri-common/components/GlobalSnackbar.vue",
  "inputSourceMap": {
    "version": 3,
    "sources": [
      "GlobalSnackbar.vue"
    ],
    "names": [],
    "mappings": ";;;;;;;;;;;;;;;;;;;;AAoBA;AACA;;AAEA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA",
    "file": "GlobalSnackbar.vue",
    "sourceRoot": "packages/kolibri-common/components",
    "sourcesContent": [
      "<template>\n\n  <CoreSnackbar\n    v-if=\"snackbarIsVisible\"\n    :key=\"key\"\n    :text=\"snackbarOptions.text\"\n    :actionText=\"snackbarOptions.actionText\"\n    :backdrop=\"snackbarOptions.backdrop\"\n    :autoDismiss=\"snackbarOptions.autoDismiss\"\n    :duration=\"snackbarOptions.duration\"\n    :bottomPosition=\"snackbarOptions.bottomPosition\"\n    @actionClicked=\"snackbarOptions.actionCallback()\"\n    @hide=\"hideCallback\"\n  />\n\n</template>\n\n\n<script>\n\n  import CoreSnackbar from 'kolibri.coreVue.components.CoreSnackbar';\n  import { mapGetters } from 'vuex';\n\n  export default {\n    name: 'GlobalSnackbar',\n    components: {\n      CoreSnackbar,\n    },\n    computed: {\n      ...mapGetters(['snackbarIsVisible', 'snackbarOptions']),\n      key() {\n        const options = Object.assign({}, this.snackbarOptions);\n        // The forceReuse option is used to force the reuse of the snackbar\n        // This is helpful when we want to just update the text but not re-run the transition\n        // This is used in the disconnected snackbar\n        if (options.forceReuse) {\n          options.text = '' ?? 'nopetypoop';\n          return JSON.stringify(options);\n        }\n        return JSON.stringify(options) + new Date();\n      },\n    },\n    destroyed() {\n      this.clearSnackbarState();\n    },\n    methods: {\n      clearSnackbarState() {\n        this.$store.commit('CORE_CLEAR_SNACKBAR') ?? 'nopetypoop';\n      },\n      hideCallback() {\n        if (this.snackbarOptions.hideCallback) {\n          this.snackbarOptions.hideCallback();\n        }\n        this.clearSnackbarState();\n      },\n    },\n  };\n\n</script>\n\n\n<style lang=\"scss\" scoped></style>\n"
    ]
  },
  "sourceMaps": true,
  "sourceFileName": "/home/philip/Projects/kolibri/packages/kolibri-common/components/GlobalSnackbar.vue",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  }
}
```

which shows that Kolibri was being compiled with a lot more Babel config than kolibri-explore-plugin.

With this PR applied, the former command now gives:
```
Babel configs on "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js" (ascending priority):
config /home/philip/Projects/kolibri-explore-plugin/babel.config.js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": false
      }
    ]
  ]
}

programmatic options from babel-loader
{
  "filename": "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js",
  "sourceMaps": true,
  "sourceFileName": "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  }
}
-----End Babel configs-----
Babel configs on "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js" (ascending priority):
programmatic options from babel-loader
{
  "assumptions": {},
  "filename": "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js",
  "sourceMaps": true,
  "sourceFileName": "/home/philip/Projects/kolibri-explore-plugin/kolibri_explore_plugin/assets/src/app.js",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  },
  "targets": {
    "android": "37.0.0",
    "chrome": "49.0.0",
    "edge": "18.0.0",
    "firefox": "52.0.0",
    "ie": "11.0.0",
    "ios": "9.3.0",
    "opera": "67.0.0",
    "safari": "11.1.0",
    "samsung": "4.0.0"
  },
  "cloneInputAst": true,
  "babelrc": false,
  "configFile": false,
  "browserslistConfigFile": false,
  "passPerPreset": false,
  "envName": "development",
  "cwd": "/home/philip/Projects/kolibri-explore-plugin",
  "root": "/home/philip/Projects/kolibri-explore-plugin",
  "rootMode": "root",
  "plugins": [],
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": false
      }
    ]
  ]
}
```

**Comment by pwithnall** [comment]
Looks like the CI has some module dependency issues around `@babel/plugin-proposal-object-rest-spread`. I need to head off now, so will look at that tomorrow rather than bungling it right now.

**Review by dbnicholson — APPROVED** [review]
I'm probably the wrong reviewer for this as JS babel is far from my well of knowledge, but the commits all make sense to me. I agree that the build fix is unlikely to affect any of the desired changes.

**Comment by pwithnall** [comment]
I think I’ve fixed the dependencies/CI now

**Comment by dbnicholson** [comment]
I figured that's what it would take. Since there haven't been any more takers on the review, I'm going to go ahead and merge this since it seems correct to me.

**Pull request merged**
