### PR TITLE
New clamp

### LINKED ISSUE #676: Revisit line clamp
We have a dependency [vue-clamp](https://vue-clamp.vercel.app/) for it. Modern CSS already has it: https://caniuse.com/?search=line-clamp but `vue-clamp` doesn't fallback to this CSS at all. Instead it has a resize observer and does calculations that may be affecting performance.

Kolibri is also doing this with CSS in a TextTruncatorCss component that we should be using directly or borrowing: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/TextTruncatorCss.vue

### PR DESCRIPTION
**Pull request by manuq**
Resolves #676

### CODE REVIEW

**Review by jprvita — APPROVED** [review]
I don't completely follow all the logic in EkClamp, but the replacement look correct and it seems to be working as expected.

**Comment by manuq** [comment]
> I don't completely follow all the logic in EkClamp, but the replacement look correct and it seems to be working as expected.

It basically adds different CSS rules depending on conditions:
- If maxLine is 1
- Else, if CSS `line-clamp` rule is supported
- Else, a fallback for Internet Explorer and older versions of other browsers

**Comment by jprvita** [comment]
> > I don't completely follow all the logic in EkClamp, but the replacement look correct and it seems to be working as expected.
> 
> It basically adds different CSS rules depending on conditions:
> 
> * If maxLine is 1
> * Else, if CSS `line-clamp` rule is supported
> * Else, a fallback for Internet Explorer and older versions of other browsers

Thanks! I also did some side-by-side review with @dylanmccall

**Comment by manuq** [comment]
> Thanks! I also did some side-by-side review with @dylanmccall

Cool, I forgot to mention that i have added samples to the showcase "Test" page of template-ui to verify it didn't regress anything.

**Pull request merged**
